### PR TITLE
Fix passing duplicate argument to global_route

### PR DESCRIPTION
**Pull request by slavashw**
in function from_ah_attr.
Caought by tests.verbs.umad_self_test.test_basic

Signed-off-by: Slava Shwartsman <valyushash@gmail.com>
Signed-off-by: Roi Dayan <roi.dayan@gmail.com>

### CODE REVIEW

**Comment by jgunthorpe** [comment]
Is this failure a side effect of converting to cython?

**Comment by slavashw** [comment]
The bug was there with or without Cython.
The only guess I have, is that Cython helped to reveal it.

**Comment by roidayan** [comment]
Hi @jgunthorpe 

this is a python issue not related to pyrex nor cython.

the following example shows the problem that you can't repeat the assignment.

```
>>> def a(a,b,c):
...  pass
... 
>>> 
>>> a(a=1,a=1,b=2,c=3)
  File "<stdin>", line 1
SyntaxError: keyword argument repeated
>>> 
```

this is what the commit is fixing.

thanks

**Comment by jgunthorpe** [comment]
It looks like Pyrex was accepting the bogus syntax silently because the test suite ran to completion. Cython is more strict.

Got it, thanks.

**Pull request closed without merging**
